version: '3.8'

name: marchepublic
services:
  app:

    container_name: marchepublic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9090:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_LIQUIBASE_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - marchepublic
      -

  postgres:
    container_name: dev
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=marchepublic'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d marchepublic"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - marchepublic

volumes:
  postgres_data:
    driver: local

networks:
  marchepublic:
    driver: bridge